### ISSUE TITLE
Failed to connect to the peer

### ISSUE THREAD

**Issue by blocknodehub** [KYVENetwork/chain#75]
I started a v1.2.1 main network node, but could not connect to the peer

persistent_peers = "b950b6b08f7a6d5c3e068fcd263802b336ffe047@18.198.182.214:26656,25da6253fc8740893277630461eb34c2e4daf545@3.76.244.30:26656,146d27829fd240e0e4672700514e9835cb6fdd98@34.212.201.1:26656,fae8cd5f04406e64484a7a8b6719eacbb861c094@44.241.103.199:26656,cca92eeb43850b9572025da5ecaae6e4703925e2@185.172.191.11:26656,307f4024107ef114dba355fe97dab44b8b45cefc@38.242.253.58:29656,16f14494d00e9f32de66207332be10b22dc5ff16@65.109.104.118:61356,abd78598669172e674b5fa93be48c8bde6361c5e@146.59.85.223:11056,5ce11995f9cc12a7a9d4370a7a1caeb37bfe24ca@35.161.244.76:26656,fae8cd5f04406e64484a7a8b6719eacbb861c094@44.241.103.199:26656,b950b6b08f7a6d5c3e068fcd263802b336ffe047@18.198.182.214:26656"

[statesync]
# State sync rapidly bootstraps a new node by discovering, fetching, and restoring a state machine
# snapshot from peers instead of fetching and replaying historical blocks. Requires some peers in
# the network to take and serve state machine snapshots. State sync is not attempted if the node
# has any local state (LastBlockHeight > 0). The node will have a truncated block history,
# starting from the height of the snapshot.
enable = true

# RPC servers (comma-separated) for light client verification of the synced state machine and
# retrieval of state data for node bootstrapping. Also needs a trusted height and corresponding
# header hash obtained from a trusted source, and a period during which validators can be trusted.
#
# For Cosmos SDK-based chains, trust_period should usually be about 2/3 of the unbonding time (~2
# weeks) during which they can be financially punished (slashed) for misbehavior.
rpc_servers = "https://rpc-cache.kyve.network:443,https:rpc-cache.kyve.network:443"
trust_height = 1140000
trust_hash = "C3EE5BF442E801DF4F8E42FC2AA458153D98EAEAA0C791F1302554CB4A5E8272"
trust_period = "168h0m0s"

**Comment by mbreithecker** [comment]
Hey @blocknodehub ,

so the peers list looks good. However, it is very likely that the nodes have reached their maximum of inbound peers. It should resolve after some time. There are also some seed nodes available. Once your node is connected to the gossip network it should receive enough peers.

When posting config files, please use a code-textbox. Otherwise all the "#"s are converted to headlines.
For your trust_height use the most recent height - 200 and the corresponding block hash.
The rest looks correct.

Let me know if it works.
